Repository larq/compute-engine, pull requests merged in 2020-11, with the labels that each got.

#558 Fix manylinux release build
  .github/workflows/release.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#549 Add grouped binary convolution support (1/3): the converter.
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/tests/bitpack-weights.mlir
  larq_compute_engine/mlir/tests/legalize-lce.mlir
  larq_compute_engine/mlir/tests/op-removal.mlir
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/tests/quantize.mlir
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/prepare_tf.cc
Labels: feature

#559 Update bazelisk version on CI and in containers.
  .github/tools/release_linux.sh
  .github/workflows/unittests.yml
  Dockerfile
Labels: dependencies

#560 Create a lightweight `BConv2DParams` struct in `/core`.
  larq_compute_engine/core/bconv2d/BUILD
  larq_compute_engine/core/bconv2d/optimized_indirect_bgemm.h
  larq_compute_engine/core/bconv2d/params.h
  larq_compute_engine/core/bconv2d/reference.h
  larq_compute_engine/core/indirect_bgemm/BUILD
  larq_compute_engine/core/indirect_bgemm/kernel.h
  larq_compute_engine/core/indirect_bgemm/prepare.h
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_output_transform_utils.h
  larq_compute_engine/tflite/kernels/bconv2d_params.h
Labels: internal-improvement

#561 Fix filter tensor shapes in bconv2d 'death' tests.
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement

#550 Add grouped binary convolution support (2/3): reference kernel.
  larq_compute_engine/core/bconv2d/optimized_bgemm.h
  larq_compute_engine/core/bconv2d/params.h
  larq_compute_engine/core/bconv2d/reference.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/tests/bconv2d_op_model.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: feature

#563 :arrow_up: tensorflow@2.4.0rc1
  WORKSPACE
Labels: dependencies

#565 Remove unused dependencies
  .bazelrc
  larq_compute_engine/mlir/BUILD
Labels: internal-improvement

#566 Set --linkopt=-dead_strip when building mac wheels
  .github/workflows/release.yml
Labels: internal-improvement

#570 Do not pin official GitHub actions
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#571 Add zero-padding support to the reference kernel
  larq_compute_engine/core/bconv2d/reference.h
  larq_compute_engine/tests/end2end_test.py
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/lce_ops_register.h
  larq_compute_engine/tflite/python/interpreter.py
  larq_compute_engine/tflite/python/interpreter_wrapper_lite.cc
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: feature

#572 Do not pin official GitHub actions
  .github/workflows/release.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#574 Only upload cache on master branch
  .github/workflows/unittests.yml
Labels: internal-improvement
