Repository larq/compute-engine, pull requests merged in 2020-08, with the labels that each got.

#451 Add Android AAR build to release workflow
  .github/workflows/release.yml
Labels: internal-improvement

#432 Add ARM32 kernel implementation
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bgemm_kernels_arm32.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: feature

#443 Add optimised canonical bitpacking for Aarch64. Closes #435.
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/macros.h
  larq_compute_engine/core/packbits.h
  larq_compute_engine/core/packbits_aarch64.h
  larq_compute_engine/core/packbits_utils.h
  larq_compute_engine/core/tests/packbits_aarch64_tests.cc
  larq_compute_engine/core/tests/packbits_tests.cc
  larq_compute_engine/core/types.h
  larq_compute_engine/mlir/transforms/bitpack_weights.cc
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/kernels/bmaxpool.cc
  larq_compute_engine/tflite/tests/bconv2d_int8_test.cc
  larq_compute_engine/tflite/tests/bconv2d_op_model.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
  larq_compute_engine/tflite/tests/bmaxpool_test.cc
Labels: internal-improvement

#449 Support full int8 QAT models in converter
  .github/workflows/unittests.yml
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/python/converter.py
  larq_compute_engine/mlir/python/graphdef_tfl_flatbuffer.cc
  larq_compute_engine/mlir/python/schema_py_generated.py
  larq_compute_engine/mlir/python/util.py
  larq_compute_engine/tests/end2end_test.py
  setup.py
Labels: feature

#453 Prebuild AArch32 benchmark binary for new releases
  .github/workflows/release.yml
Labels: internal-improvement

#455 add extra braces around padding_buffer
  larq_compute_engine/core/packbits.h
Labels: internal-improvement

#461 Standardise on 32-bit bitpacking. Closes #446.
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bconv2d_impl_ref.h
  larq_compute_engine/core/bconv2d_output_transform.h
  larq_compute_engine/core/bgemm_functor.h
  larq_compute_engine/core/bgemm_impl.h
  larq_compute_engine/core/bgemm_impl_ref.h
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bgemm_kernels_arm32.h
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/core/bgemm_kernels_x86.h
  larq_compute_engine/core/bgemm_trmul_params.h
  larq_compute_engine/core/bmaxpool.h
  larq_compute_engine/core/packbits.h
  larq_compute_engine/core/packbits_aarch64.h
  larq_compute_engine/core/packbits_utils.h
  larq_compute_engine/core/tests/BUILD
  larq_compute_engine/core/tests/bgemm_tests.cc
  larq_compute_engine/core/tests/packbits_aarch64_tests.cc
  larq_compute_engine/core/tests/packbits_tests.cc
  larq_compute_engine/core/types.h
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/transforms/bitpack_weights.cc
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/kernels/bconv2d_output_transform_utils.h
  larq_compute_engine/tflite/kernels/bconv2d_params.h
  larq_compute_engine/tflite/kernels/bmaxpool.cc
  larq_compute_engine/tflite/tests/BUILD
  larq_compute_engine/tflite/tests/bconv2d_int8_test.cc
  larq_compute_engine/tflite/tests/bconv2d_op_model.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
  larq_compute_engine/tflite/tests/bmaxpool_test.cc
  larq_compute_engine/tflite/tests/utils.h
Labels: internal-improvement

#456 Automatically upload benchmark binaries to new releases
  .github/workflows/release.yml
Labels: internal-improvement

#462 Improve performance with optimised Ruy matrix packing.
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_trmul_params.h
  larq_compute_engine/core/ruy_pack.h
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
Labels: performance

#463 Rename `packbits` to `bitpack` for consistency.
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/core/bitpack.h
  larq_compute_engine/core/bitpack_aarch64.h
  larq_compute_engine/core/bitpack_utils.h
  larq_compute_engine/core/tests/BUILD
  larq_compute_engine/core/tests/bitpack_aarch64_tests.cc
  larq_compute_engine/core/tests/bitpack_tests.cc
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/transforms/bitpack_weights.cc
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/kernels/bmaxpool.cc
  larq_compute_engine/tflite/tests/BUILD
  larq_compute_engine/tflite/tests/bconv2d_test.cc
  larq_compute_engine/tflite/tests/bmaxpool_test.cc
Labels: internal-improvement

#464 Change custom option enums to match flatbuffer schema
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/ir/lce_ops.cc
  larq_compute_engine/mlir/tests/BUILD
  larq_compute_engine/mlir/tests/lce_ops_options_test.cc
  larq_compute_engine/mlir/tests/legalize-lce.mlir
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bmaxpool.cc
  larq_compute_engine/tflite/kernels/utils.cc
  larq_compute_engine/tflite/kernels/utils.h
  larq_compute_engine/tflite/tests/bconv2d_op_model.h
  larq_compute_engine/tflite/tests/bmaxpool_test.cc
  larq_compute_engine/tflite/tests/utils.h
Labels: breaking-change

#465 Fix unittest linkopts for macos
  larq_compute_engine/core/tests/BUILD
Labels: internal-improvement

#472 Simplify shape handling in kernel prepare method
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bmaxpool.cc
  larq_compute_engine/tflite/kernels/quantization.cc
Labels: internal-improvement

#473 Remove output shape argument from bitpack_tensor
  larq_compute_engine/core/bitpack_utils.h
  larq_compute_engine/tflite/kernels/quantization.cc
  larq_compute_engine/tflite/tests/bconv2d_test.cc
  larq_compute_engine/tflite/tests/bmaxpool_test.cc
Labels: internal-improvement

#474 Directly pass packed filer shape to bconv kernel
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
Labels: internal-improvement

#475 Remove input/output dimensions from BConvParams
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_params.h
Labels: internal-improvement

#470 Update benchmark table in Readme
  README.md
Labels: documentation

#476 Remove Windows builds from release workflow
  .github/workflows/release.yml
Labels: internal-improvement

#471 Add profiler scopes for bitpacking functions and quantization/maxpool ops.
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/core/bitpack.h
  larq_compute_engine/core/bitpack_aarch64.h
  larq_compute_engine/core/bitpack_utils.h
  larq_compute_engine/core/padding_functor.h
  larq_compute_engine/core/tests/bitpack_tests.cc
  larq_compute_engine/mlir/ir/lce_ops.cc
  larq_compute_engine/mlir/transforms/bitpack_weights.cc
  larq_compute_engine/mlir/transforms/optimize.cc
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bmaxpool.cc
  larq_compute_engine/tflite/kernels/quantization.cc
  larq_compute_engine/tflite/tests/bconv2d_test.cc
  larq_compute_engine/tflite/tests/bmaxpool_test.cc
  larq_compute_engine/tflite/tests/quantization_test.cc
Labels: internal-improvement

#477 Remove lce_benchmark_all binary
  examples/lce_minimal.cc
  larq_compute_engine/tflite/benchmark/BUILD
  larq_compute_engine/tflite/benchmark/lce_benchmark_all.cc
Labels: internal-improvement

#478 Remove zero_point argument from im2col
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
Labels: internal-improvement

#479 Update lint dependencies
  .github/workflows/lint.yml
  larq_compute_engine/mlir/python/util.py
  larq_compute_engine/tests/end2end_test.py
Labels: dependencies

#482 Change PyPI author email to opensource@plumerai.com
  setup.py
Labels: skip-changelog

#480 Simplify make build
  .github/tools/release_linux.sh
  configure.sh
  larq_compute_engine/tflite/build_make/Makefile
  larq_compute_engine/tflite/build_make/build_lce.sh
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/lce_register.cc
  larq_compute_engine/tflite/tests/BUILD
Labels: bug

#481 Update URLs in readme to adapt to the build docs changes
  README.md
Labels: documentation

#483 :arrow_up: 0.4.0
  setup.py
Labels: skip-changelog

#484 Simplify BConv2DParams by removing flags.
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_params.h
Labels: internal-improvement
