Repository larq/compute-engine, pull requests merged in 2020-09, with the labels that each got.

#486 Clean-up bconv2d by simplifying Init/Prepare/OneTimeSetup.
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_params.h
  larq_compute_engine/tflite/tests/BUILD
  larq_compute_engine/tflite/tests/bconv2d_int8_test.cc
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement

#488 Use Bazel test_filter argument instead of action_env for tests
  .github/workflows/unittests.yml
Labels: internal-improvement, test

#490 Fuse part of the back-transformation into the multiplier and bias.
  larq_compute_engine/core/bconv2d_impl_ref.h
  larq_compute_engine/core/bconv2d_output_transform.h
  larq_compute_engine/core/bgemm_impl.h
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm32.h
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/kernels/bconv2d_output_transform_utils.h
  larq_compute_engine/tflite/kernels/bconv2d_params.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: performance

#491 Fix bug in 32-bit accumulator kernel introduced by 346f72e.
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: bug

#492 Add Int8 output support to the optimised binary convolution kernels.
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bgemm_kernels_arm32.h
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: feature, performance

#494 Add an optimised Aarch64 assembly implementation of Int8 bitpacking.
  larq_compute_engine/core/bitpack.h
  larq_compute_engine/core/bitpack_aarch64.h
  larq_compute_engine/core/tests/bitpack_aarch64_tests.cc
  larq_compute_engine/core/tests/bitpack_tests.cc
Labels: performance

#495 Remove Preprocessed from OutputTransformDetails
  larq_compute_engine/core/bconv2d_output_transform.h
Labels: internal-improvement

#498 Fix typos in header guards.
  larq_compute_engine/core/bconv2d_impl_ref.h
  larq_compute_engine/core/bgemm_impl.h
  larq_compute_engine/core/bgemm_impl_ref.h
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm32.h
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/core/bgemm_trmul_params.h
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/kernels/lce_ops_register.h
Labels: skip-changelog

#496 Add bitpacked output support to the Aarch64 optimised int16 kernel.
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bgemm_kernels_arm32.h
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
Labels: feature, performance

#499 Add `inline` to `round` and `saturate`
  larq_compute_engine/core/bconv2d_output_transform.h
Labels: internal-improvement

#497 Simplify path selection and remove unnecessary kernel registrations.
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/core/bgemm_kernels_x86.h
  larq_compute_engine/core/bgemm_trmul_params.h
Labels: internal-improvement

#500 :arrow_up: 0.4.1
  setup.py
Labels: skip-changelog

#501 Fix bug introduced by #497. Make sure OPT kernels run.
  larq_compute_engine/core/bgemm_trmul_params.h
Labels: bug

#502 :arrow_up: 0.4.2
  setup.py
Labels: skip-changelog

#503 Simplify MAKE_ZERO macro
  larq_compute_engine/core/bgemm_kernels_arm32.h
  larq_compute_engine/core/bgemm_kernels_arm64.h
Labels: internal-improvement

#505 Add padding to temporary arrays to ensure we don't read beyond bounds.
  larq_compute_engine/core/types.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
Labels: internal-improvement

#507 Add Python wrapper for LCE interpreter
  .github/workflows/unittests.yml
  build_pip_pkg.sh
  larq_compute_engine/BUILD
  larq_compute_engine/__init__.py
  larq_compute_engine/mlir/python/converter_test.py
  larq_compute_engine/tests/BUILD
  larq_compute_engine/tests/end2end_test.py
  larq_compute_engine/tests/end2end_verify.cc
  larq_compute_engine/tflite/BUILD
  larq_compute_engine/tflite/__init__.py
  larq_compute_engine/tflite/python/BUILD
  larq_compute_engine/tflite/python/__init__.py
  larq_compute_engine/tflite/python/interpreter.py
  larq_compute_engine/tflite/python/interpreter_wrapper_lite.cc
  larq_compute_engine/tflite/python/interpreter_wrapper_utils.h
  larq_compute_engine/tflite/tests/BUILD
  larq_compute_engine/tflite/tests/interpreter_test.py
  setup.py
Labels: feature

#509 Make Interpreter::get_shapes and get_types more generic
  larq_compute_engine/tflite/python/interpreter_wrapper_utils.h
Labels: internal-improvement

#510 Remove redundant code paths: reference BGemm, BGemm functor.
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bconv2d_impl_ref.h
  larq_compute_engine/core/bgemm_functor.h
  larq_compute_engine/core/bgemm_impl.h
  larq_compute_engine/core/bgemm_impl_ref.h
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/core/bgemm_trmul_params.h
  larq_compute_engine/core/padding_functor.h
  larq_compute_engine/core/tests/BUILD
  larq_compute_engine/core/tests/bgemm_tests.cc
  larq_compute_engine/core/types.h
Labels: internal-improvement

#511 Add support for iterators in Interpreter.predict
  larq_compute_engine/tflite/python/interpreter.py
  larq_compute_engine/tflite/tests/interpreter_test.py
Labels: feature

#512 Add support for multi threaded interpreter
  larq_compute_engine/tests/end2end_test.py
  larq_compute_engine/tflite/python/interpreter.py
  larq_compute_engine/tflite/python/interpreter_wrapper_lite.cc
  larq_compute_engine/tflite/tests/interpreter_test.py
Labels: feature

#513 :arrow_up: 0.4.3
  setup.py
Labels: skip-changelog

#514 Reorganise `/core` directory.
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bconv2d/BUILD
  larq_compute_engine/core/bconv2d/optimized.h
  larq_compute_engine/core/bconv2d/output_transform.h
  larq_compute_engine/core/bconv2d/padding_functor.h
  larq_compute_engine/core/bconv2d/reference.h
  larq_compute_engine/core/bgemm/BUILD
  larq_compute_engine/core/bgemm/bgemm.h
  larq_compute_engine/core/bgemm/kernels.h
  larq_compute_engine/core/bgemm/kernels_aarch64.h
  larq_compute_engine/core/bgemm/kernels_arm32.h
  larq_compute_engine/core/bgemm/kernels_common.h
  larq_compute_engine/core/bgemm/ruy_pack.h
  larq_compute_engine/core/bgemm/ruy_trmul_params.h
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bitpacking/BUILD
  larq_compute_engine/core/bitpacking/bitpack.h
  larq_compute_engine/core/bitpacking/bitpack_aarch64.h
  larq_compute_engine/core/bitpacking/tests/BUILD
  larq_compute_engine/core/bitpacking/tests/bitpack_aarch64_test.cc
  larq_compute_engine/core/bitpacking/tests/bitpack_test.cc
  larq_compute_engine/core/bitpacking/utils.h
  larq_compute_engine/core/bmaxpool.h
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/ir/lce_ops.cc
  larq_compute_engine/mlir/transforms/bitpack_weights.cc
  larq_compute_engine/mlir/transforms/optimize.cc
  larq_compute_engine/tests/BUILD
  larq_compute_engine/tests/cc_tests_aarch64_qemu.sh
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_output_transform_utils.h
  larq_compute_engine/tflite/kernels/bmaxpool.cc
  larq_compute_engine/tflite/kernels/quantization.cc
  larq_compute_engine/tflite/tests/BUILD
  larq_compute_engine/tflite/tests/bconv2d_test.cc
  larq_compute_engine/tflite/tests/bmaxpool_test.cc
  larq_compute_engine/tflite/tests/quantization_test.cc
Labels: internal-improvement

#515 Simplify the bconv2d padding functor.
  larq_compute_engine/core/bconv2d/BUILD
  larq_compute_engine/core/bconv2d/optimized.h
  larq_compute_engine/core/bconv2d/padding_functor.h
  larq_compute_engine/core/bconv2d/reference.h
  larq_compute_engine/core/bconv2d/zero_padding_correction.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
Labels: internal-improvement

#516 Add optimised 'Indirect BGEMM' binary convolution kernels.
  larq_compute_engine/core/bconv2d/BUILD
  larq_compute_engine/core/bconv2d/optimized_bgemm.h
  larq_compute_engine/core/bconv2d/optimized_indirect_bgemm.h
  larq_compute_engine/core/indirect_bgemm/BUILD
  larq_compute_engine/core/indirect_bgemm/kernel.h
  larq_compute_engine/core/indirect_bgemm/kernel_4x2_portable.h
  larq_compute_engine/core/indirect_bgemm/prepare.h
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_params.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement
