Repository larq/compute-engine, pull requests merged in 2020-06, with the labels that each got.

#389 Remove RUY_ASM_FLAG_HAS_BIAS
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/core/bgemm_kernels_common.h
Labels: internal-improvement

#390 Fix sequential model in end2end test: add missing quantisers.
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/transforms/optimize.cc
  larq_compute_engine/tests/end2end_test.py
Labels: bug

#392 Add custom dev docker file
  Dockerfile
  third_party/install_android.sh
Labels: internal-improvement

#395 Add new performance label to release notes
  .github/pr_labels.yml
  .github/release-drafter.yml
Labels: internal-improvement

#394 Improve Aarch64 performance by removing NEON pipeline stalls.
  larq_compute_engine/core/bgemm_kernels_arm64.h
Labels: performance

#397 Publish dev docker images for releases
  .github/workflows/release.yml
Labels: feature

#399 Slightly optimize docker image size
  Dockerfile
Labels: internal-improvement

#398 Publish prebuilt benchmark binaries with each new release
  .github/workflows/release.yml
Labels: feature

#357 Allow to set fake default ranges to enable latency test of int8 models
  larq_compute_engine/mlir/python/converter.py
  larq_compute_engine/mlir/python/converter_test.py
  larq_compute_engine/mlir/python/graphdef_tfl_flatbuffer.cc
  larq_compute_engine/mlir/tf_tfl_passes.cc
Labels: feature

#401 Add misc updates for Micro
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bconv2d_impl_ref.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
Labels: internal-improvement

#384 Use custom larq MLIR dialect for our ops
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/ir/dialect_registration.cc
  larq_compute_engine/mlir/ir/lce_ops.cc
  larq_compute_engine/mlir/ir/lce_ops.h
  larq_compute_engine/mlir/ir/lce_ops.td
  larq_compute_engine/mlir/tests/BUILD
  larq_compute_engine/mlir/tests/bitpack-weights.mlir
  larq_compute_engine/mlir/tests/lce_ops_options_test.cc
  larq_compute_engine/mlir/tests/legalize-lce.mlir
  larq_compute_engine/mlir/tests/op-removal.mlir
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/tests/quantize.mlir
  larq_compute_engine/mlir/tf_tfl_passes.cc
  larq_compute_engine/mlir/transforms/bitpack_weights_patterns.td
  larq_compute_engine/mlir/transforms/legalize_tflite.cc
  larq_compute_engine/mlir/transforms/op_removal.cc
  larq_compute_engine/mlir/transforms/op_removal_patterns.td
  larq_compute_engine/mlir/transforms/optimize.cc
  larq_compute_engine/mlir/transforms/optimize_patterns.td
  larq_compute_engine/mlir/transforms/passes.h
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/quantize_patterns.td
Labels: internal-improvement

#402 Fix trailing quantization op with experimental_bitpacking fusion
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/tests/quantize.mlir
  larq_compute_engine/mlir/tf_tfl_passes.cc
  larq_compute_engine/mlir/transforms/passes.h
  larq_compute_engine/mlir/transforms/quantize.cc
  larq_compute_engine/mlir/transforms/quantize_patterns.td
Labels: bug

#386 Set padding and fused activations as enums
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/ir/lce_ops.cc
  larq_compute_engine/mlir/tests/BUILD
  larq_compute_engine/mlir/tests/lce_ops_options_test.cc
  larq_compute_engine/mlir/tests/legalize-lce.mlir
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bmaxpool.cc
  larq_compute_engine/tflite/tests/bconv2d_op_model.h
  larq_compute_engine/tflite/tests/bmaxpool_test.cc
  larq_compute_engine/tflite/tests/utils.h
Labels: breaking-change

#413 Fix broken links
  README.md
Labels: documentation

#403 Replace context->ReportError calls with TF_LITE_KERNEL_LOG
  larq_compute_engine/tflite/kernels/bconv2d.cc
Labels: internal-improvement
