Repository larq/compute-engine, pull requests merged in 2020-03, with the labels that each got.

#256 Update BConv TableGen definition to match TFLite Op
  larq_compute_engine/mlir/ir/lce_ops.td
Labels: internal-improvement

#254 Support running lit tests on macOS without needing to install GNU find
  .github/workflows/unittests.yml
  larq_compute_engine/mlir/tests/run_lit.sh
Labels: internal-improvement

#255 Cleanup MLIR tests
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/tests/prepare-tf.mlir
Labels: internal-improvement

#253 Simplify is binary check
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/prepare_tf.cc
Labels: internal-improvement

#259 Add core tests back to CI
  .github/workflows/unittests.yml
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/tests/BUILD
  larq_compute_engine/core/tests/im2col_tests.cc
Labels: internal-improvement, test

#252 Add support for one-padding
  larq_compute_engine/mlir/ir/lce_ops.td
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/transforms/optimize_patterns.td
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/prepare_tf.cc
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: feature

#262 moving xor-popcount functions to bgemm popcount-related functions collection
  larq_compute_engine/core/bgemm_functor.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
Labels: internal-improvement, skip-changelog

#261 remove legacy reference impl. of LCE bconv op
  larq_compute_engine/core/bconv2d_functor.h
  larq_compute_engine/core/benchmark/BUILD
  larq_compute_engine/core/benchmark/bconv2d_bench.cc
  larq_compute_engine/core/benchmark/bgemm_bench.cc
  larq_compute_engine/core/benchmark/im2col_bench.cc
  larq_compute_engine/core/fused_bgemm_functor.h
  larq_compute_engine/core/tests/BUILD
  larq_compute_engine/core/tests/bconv2d_tests.cc
  larq_compute_engine/core/tests/fused_bgemm_tests.cc
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
Labels: internal-improvement

#265 Run CI on PRs (including from forks).
  .github/workflows/lint.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#264 Simplify padding constraint
  larq_compute_engine/mlir/transforms/prepare_patterns.td
Labels: internal-improvement

#266 Add LCE meta info to README
  README.md
Labels: skip-changelog

#260 Split fused multiply into backtransform and post multiply
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/core/padding_functor.h
  larq_compute_engine/mlir/ir/lce_ops.td
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/transforms/optimize_patterns.td
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/prepare_tf.cc
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement

#263 Reduce normal register loads
  larq_compute_engine/core/bgemm_kernels_arm64.h
Labels: internal-improvement

#271 Run ARM tests with debug builds. Closes #270.
  .github/workflows/unittests.yml
  configure.sh
Labels: internal-improvement

#272 Remove un-used variable, fix typo.
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement

#273 Cleanup LCE AAR build
  .github/workflows/unittests.yml
  larq_compute_engine/tflite/java/build_lce_aar.sh
Labels: internal-improvement

#274 remove armv7 android ABI from LCE Lite AAR
  larq_compute_engine/tflite/java/build_lce_aar.sh
Labels: internal-improvement

#268 Replace mul + add with shl + sub
  larq_compute_engine/core/bgemm_kernels_arm64.h
Labels: internal-improvement

#277 Merge some bconv test params (as the # of params is limited).
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement, test

#267 Fused activation
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/mlir/ir/lce_ops.td
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/transforms/optimize.cc
  larq_compute_engine/mlir/transforms/optimize_patterns.td
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: feature

#269 Add end2end test
  .github/workflows/unittests.yml
  larq_compute_engine/tests/BUILD
  larq_compute_engine/tests/end2end_test.py
  larq_compute_engine/tests/end2end_verify.cc
Labels: internal-improvement, test

#280 Switch converter tests to be Python only
  .github/workflows/unittests.yml
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/python/converter_test.py
Labels: internal-improvement

#282 (ci-skip) Simplify pip package publishing
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: internal-improvement

#283 Add +1 padding to the end2end test
  .github/workflows/unittests.yml
  examples/converter_examples.py
  larq_compute_engine/mlir/python/converter_test.py
  larq_compute_engine/tests/end2end_test.py
Labels: internal-improvement

#288 Use `fastbuild` instead of `dbg` for tests.
  .github/workflows/unittests.yml
  configure.sh
Labels: internal-improvement, test

#287 Enable Bazel GCS remote cache
  .github/workflows/unittests.yml
Labels: internal-improvement

#291 Add preprocessor statement to fix warning
  larq_compute_engine/core/bgemm_kernels_ruy.h
Labels: internal-improvement

#289 Consolidate TFLite and core CC tests to improve test parallelization
  .github/workflows/unittests.yml
  larq_compute_engine/core/tests/BUILD
  larq_compute_engine/tests/BUILD
  larq_compute_engine/tests/cc_tests_aarch64_qemu.sh
  larq_compute_engine/tests/cc_tests_arm32_qemu.sh
  larq_compute_engine/tflite/tests/BUILD
  larq_compute_engine/tflite/tests/cc_tests_aarch64_qemu.sh
  larq_compute_engine/tflite/tests/cc_tests_arm32_qemu.sh
Labels: internal-improvement

#295 Fix typo that caused 64-bit op on ARM32
  larq_compute_engine/tflite/kernels/bconv2d.cc
Labels: bug

#294 update the benchmark results
  README.md
Labels: documentation

#300 :arrow_up: v0.2.0
  setup.py
Labels: skip-changelog

#298 Consolidate MLIR and End2End tests
  .github/workflows/unittests.yml
Labels: internal-improvement

#301 Don't use cache if authentication fails
  .github/workflows/unittests.yml
Labels: internal-improvement

#299 Fix docs link in contributing guide
  CONTRIBUTING.md
Labels: documentation

#303 Fix typos and standardise std:: namespace usage.
  larq_compute_engine/core/benchmark/aarch64/packbits_bench.cc
  larq_compute_engine/core/benchmark/bgemm_bench.cc
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/core/bgemm_trmul_params.h
  larq_compute_engine/core/packbits.h
  larq_compute_engine/core/packbits_aarch64.h
  larq_compute_engine/core/packbits_arm32.h
  larq_compute_engine/core/padding_functor.h
  larq_compute_engine/core/tests/bgemm_arm32_tests.cc
  larq_compute_engine/core/tests/bgemm_tests.cc
  larq_compute_engine/core/tests/packbits_aarch64_tests.cc
  larq_compute_engine/core/tests/packbits_arm32_tests.cc
  larq_compute_engine/core/tests/packbits_tests.cc
  larq_compute_engine/mlir/transforms/optimize.cc
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/kernels/sign.cc
  larq_compute_engine/tflite/kernels/utils.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement

#304 add header guard for bconv impl
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
Labels: internal-improvement

#307 remove obsolete bazel build targets
  larq_compute_engine/core/BUILD
Labels: internal-improvement, skip-changelog

#306 (ci-skip) Fix comment typos.
  larq_compute_engine/core/bgemm_kernels_arm64.h
Labels: skip-changelog

#308 Consolidate four vector register loads into one instruction.
  larq_compute_engine/core/bgemm_kernels_arm64.h
Labels: internal-improvement

#310 Add MLIR status handler to log converter errors
  larq_compute_engine/mlir/python/graphdef_tfl_flatbuffer.cc
Labels: internal-improvement

#311 move the packbit utils to core dir
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/packbits_utils.h
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
Labels: skip-changelog

#309 (skip-ci) Add missing copyright notice.
  larq_compute_engine/tflite/kernels/lce_register.cc
Labels: skip-changelog

#312 fix the header guard for packbit utils
  larq_compute_engine/core/packbits_utils.h
Labels: internal-improvement

#315 (ci-skip) Correct model accuracies
  README.md
Labels: documentation

#316 Remove un-used variable.
  larq_compute_engine/core/bgemm_kernels_common.h
Labels: skip-changelog

#318 set bazel as default builder for android AAR
  larq_compute_engine/tflite/java/build_lce_aar.sh
Labels: internal-improvement

#319 (ci-skip) Correct top-1 accuracies according to #315
  README.md
Labels: documentation

#314 Add reference implementation of binary convolution.
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bconv2d_impl_ref.h
  larq_compute_engine/core/packbits_utils.h
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/tests/BUILD
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: feature
