Repository larq/compute-engine, pull requests merged in 2020-04, with the labels that each got.

#320 fix dependency for ref. bconv
  larq_compute_engine/core/BUILD
Labels: internal-improvement

#321 Switch CI testing from mac to linux
  .github/workflows/unittests.yml
Labels: internal-improvement

#322 Run AAR test outside the custom op container
  .github/workflows/unittests.yml
Labels: internal-improvement

#313 Add ImageNet evaluation tool from TFLite
  .github/workflows/unittests.yml
  larq_compute_engine/tflite/tools/accuracy/ilsvrc/BUILD
  larq_compute_engine/tflite/tools/accuracy/ilsvrc/README.md
  larq_compute_engine/tflite/tools/accuracy/ilsvrc/imagenet_model_evaluator.cc
  larq_compute_engine/tflite/tools/evaluation/stages/BUILD
  larq_compute_engine/tflite/tools/evaluation/stages/image_preprocessing_stage.cc
  larq_compute_engine/tflite/tools/evaluation/stages/tflite_inference_stage.cc
Labels: feature

#323 Update dead download link in README
  larq_compute_engine/tflite/tools/accuracy/ilsvrc/README.md
Labels: skip-changelog

#326 Support weight scaling in converter
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/prepare_tf.cc
Labels: feature

#305 Support reading and writing bitpacked activations in C++ kernels.
  larq_compute_engine/core/bconv2d_impl_ref.h
  larq_compute_engine/core/bgemm_impl_ruy.h
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
  larq_compute_engine/core/bgemm_kernels_x86.h
  larq_compute_engine/tflite/build_make/Makefile
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/tests/BUILD
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: feature

#328 Fix bug from 24df15a.
  larq_compute_engine/tflite/kernels/bconv2d.cc
Labels: skip-changelog

#329 Consistently use bazel test and --test_output=all on CI
  .github/workflows/unittests.yml
  larq_compute_engine/tests/BUILD
Labels: internal-improvement

#330 Simplify ARM compiler build files
  WORKSPACE
  larq_compute_engine/tests/BUILD
  third_party/aarch64_compiler.BUILD
  third_party/arm_compiler.BUILD
  third_party/toolchains/cpus/arm/BUILD
Labels: internal-improvement

#332 AArch64 BMLA: Use pairwise addition to accumulate popcount results
  larq_compute_engine/core/bgemm_kernels_arm64.h
Labels: internal-improvement

#334 (ci-skip) Fix typo
  README.md
Labels: documentation

#335 Fix broken links
  README.md
Labels: documentation

#337 Add bitpack order argument to packbits_tensor
  larq_compute_engine/core/packbits_utils.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement

#338 Fix GTEST_FILTER on CI
  .github/workflows/unittests.yml
Labels: internal-improvement

#340 :arrow_up: 0.2.1
  setup.py
Labels: skip-changelog

#341 Update README with QuickNet Correction
  README.md
Labels: documentation

#342 :arrow_up: lint dependencies
  .github/workflows/lint.yml
  .github/workflows/unittests.yml
  larq_compute_engine/tests/end2end_test.py
Labels: internal-improvement
