Repository larq/compute-engine, pull requests merged in 2020-10, with the labels that each got.

#518 Add optimised indirect bgemm kernels for Aarch64.
  larq_compute_engine/core/indirect_bgemm/BUILD
  larq_compute_engine/core/indirect_bgemm/kernel.h
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x1_aarch64.h
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x2_aarch64.h
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x4_aarch64.h
  larq_compute_engine/core/indirect_bgemm/prepare.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: performance

#519 Add support for batched inputs in the indirect BGEMM kernels
  larq_compute_engine/core/bconv2d/optimized_indirect_bgemm.h
  larq_compute_engine/core/indirect_bgemm/prepare.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement

#521 Slightly optimise the loads in the 8x4x2 indirect BGEMM kernel
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x2_aarch64.h
Labels: performance

#523 Fix minor formatting issue in `optimize_patterns.td`
  larq_compute_engine/mlir/transforms/optimize_patterns.td
Labels: skip-changelog

#524 Initialise batch norm stats for e2e models
  larq_compute_engine/tests/end2end_test.py
Labels: internal-improvement, test

#525 Run LCE optimize pass before and after TFLite optimize pass
  larq_compute_engine/mlir/tf_tfl_passes.cc
Labels: bug

#528 Inline kernel utils functions that convert padding and activation enums
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/utils.cc
  larq_compute_engine/tflite/kernels/utils.h
Labels: internal-improvement

#532 Prebuild the benchmark binary with -O3 on Android
  .bazelrc
  .github/workflows/release.yml
  larq_compute_engine/core/bgemm/ruy_pack.h
Labels: internal-improvement

#530 Add macros to help GCC with branch prediction
  larq_compute_engine/core/indirect_bgemm/kernel_4x2_portable.h
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x1_aarch64.h
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x2_aarch64.h
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x4_aarch64.h
  larq_compute_engine/core/types.h
Labels: internal-improvement

#534 Move padding conversion function to kernels/utils.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/utils.h
Labels: internal-improvement

#536 Update Flatbuffer schema for TF 2.4
  larq_compute_engine/mlir/python/schema_py_generated.py
Labels: internal-improvement

#543 Add __version__ property.
  larq_compute_engine/__init__.py
  larq_compute_engine/mlir/python/converter_test.py
  setup.py
Labels: internal-improvement

#546 Auto-generate the TFLite Python schema.
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/python/converter_test.py
  larq_compute_engine/mlir/python/schema_py_generated.py
  larq_compute_engine/mlir/python/util.py
Labels: internal-improvement

#547 :arrow_up: larq_zoo@v2
  .github/workflows/unittests.yml
  larq_compute_engine/tests/end2end_test.py
Labels: internal-improvement

#552 Speedup end2end tests
  larq_compute_engine/tests/end2end_test.py
Labels: internal-improvement, test

#555 :arrow_up: lint dependencies
  .github/workflows/lint.yml
  larq_compute_engine/core/bconv2d/output_transform.h
  larq_compute_engine/core/bitpacking/bitpack_aarch64.h
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x1_aarch64.h
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x2_aarch64.h
  larq_compute_engine/core/indirect_bgemm/kernel_8x4x4_aarch64.h
Labels: dependencies

#556 Cancel workflows of outdated commits
  .github/workflows/unittests.yml
Labels: internal-improvement
