Repository larq/compute-engine, pull requests merged in 2020-05, with the labels that each got.

#346 Setup possibility to build nightly wheels on CI
  .github/workflows/release.yml
Labels: internal-improvement

#347 Add support for prebuilt Python 3.8 wheels
  .github/tools/release_linux.sh
  .github/workflows/release.yml
  setup.py
Labels: feature

#348 Add TF 2.2 to converter test matrix
  .github/workflows/unittests.yml
Labels: internal-improvement

#343 Reformat summaries in python.converter.py
  larq_compute_engine/mlir/python/converter.py
Labels: documentation

#331 Upgrade ARM gcc compiler to 9.2.1
  WORKSPACE
  larq_compute_engine/tests/cc_tests_aarch64_qemu.sh
  third_party/arm_compiler.BUILD
  third_party/toolchains/cpus/arm/cc_config.bzl.tpl
Labels: internal-improvement

#354 Use pre-installed bazelisk on CI
  .github/workflows/release.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#353 Build wheels using AVX support
  .github/tools/release_linux.sh
  .github/workflows/release.yml
  configure.sh
  third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0/windows/msvc_wrapper_for_nvcc.py
  third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.1/BUILD
  third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.1/cc_toolchain_config.bzl
  third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.1/clang/bin/crosstool_wrapper_driver_is_not_gcc
Labels: internal-improvement

#355 Build wheels for Windows
  .github/workflows/release.yml
  MANIFEST.in
  build_pip_pkg.sh
  configure.sh
Labels: feature

#350 Add 8x4 Arm64 kernel to improve performance
  larq_compute_engine/core/bconv2d_output_transform.h
  larq_compute_engine/core/bgemm_kernels_arm.h
  larq_compute_engine/core/bgemm_kernels_arm64.h
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/core/bgemm_trmul_params.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_output_transform_utils.h
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement

#359 Update benchmark results
  README.md
Labels: documentation

#360 :arrow_up: 0.3.0
  setup.py
Labels: skip-changelog

#361 Make PyPI release condition less strict
  .github/workflows/release.yml
Labels: internal-improvement

#366 Simplify WORKSPACE and remove old third_party files.
  WORKSPACE
  configure.sh
  larq_compute_engine/core/benchmark/BUILD
  larq_compute_engine/core/benchmark/aarch64/packbits_bench.cc
  larq_compute_engine/core/benchmark/bgemm_bench.cc
  larq_compute_engine/core/benchmark/padding_bench.cc
  third_party/gpu/BUILD
  third_party/gpu/crosstool/BUILD
  third_party/gpu/crosstool/BUILD.tpl
  third_party/gpu/crosstool/CROSSTOOL.tpl
  third_party/gpu/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl
  third_party/gpu/crosstool/windows/msvc_wrapper_for_nvcc.py.tpl
  third_party/gpu/cuda/BUILD
  third_party/gpu/cuda/BUILD.tpl
  third_party/gpu/cuda/BUILD.windows.tpl
  third_party/gpu/cuda/build_defs.bzl.tpl
  third_party/gpu/cuda/cuda_config.h.tpl
  third_party/gpu/cuda_configure.bzl
  third_party/tf/BUILD
  third_party/tf/BUILD.tpl
  third_party/tf/tf_configure.bzl
Labels: internal-improvement

#367 Simplify .bazelrc and configure.sh
  .bazelrc
  .gitignore
  configure.sh
Labels: internal-improvement

#356 Add support for int8 quantization aware training
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/python/converter.py
  larq_compute_engine/mlir/python/converter_test.py
  larq_compute_engine/mlir/python/graphdef_tfl_flatbuffer.cc
  larq_compute_engine/mlir/tests/quantize.mlir
  larq_compute_engine/mlir/tf_tfl_passes.cc
  larq_compute_engine/mlir/tf_tfl_passes.h
  larq_compute_engine/mlir/transforms/passes.h
  larq_compute_engine/mlir/transforms/quantize.cc
  larq_compute_engine/mlir/transforms/quantize_patterns.td
  larq_compute_engine/tests/end2end_test.py
Labels: feature

#365 Add binary maxpool 2D op
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/bmaxpool.h
  larq_compute_engine/core/packbits_aarch64.h
  larq_compute_engine/tflite/kernels/BUILD
  larq_compute_engine/tflite/kernels/bmaxpool.cc
  larq_compute_engine/tflite/kernels/lce_ops_register.h
  larq_compute_engine/tflite/kernels/lce_register.cc
  larq_compute_engine/tflite/tests/BUILD
  larq_compute_engine/tflite/tests/bmaxpool_test.cc
  larq_compute_engine/tflite/tests/utils.h
Labels: feature

#368 Move RUY profiling out of core files
  larq_compute_engine/core/bgemm_functor.h
  larq_compute_engine/core/packbits_utils.h
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_impl.h
Labels: internal-improvement

#364 Add converter support for a binarised maxpool op `LceBMaxPool2d`.
  larq_compute_engine/mlir/ir/lce_ops.td
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/transforms/optimize.cc
  larq_compute_engine/tests/end2end_test.py
Labels: feature

#369 Add binary maxpool dead op cleanup pattern.
  larq_compute_engine/mlir/tests/op-removal.mlir
  larq_compute_engine/mlir/transforms/op_removal_patterns.td
Labels: bug

#370 Remove unused data_format attribute from IR
  WORKSPACE
  larq_compute_engine/mlir/ir/lce_ops.td
  larq_compute_engine/mlir/tests/op-removal.mlir
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/tests/quantize.mlir
  larq_compute_engine/mlir/transforms/op_removal_patterns.td
  larq_compute_engine/mlir/transforms/optimize_patterns.td
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/quantize_patterns.td
Labels: internal-improvement

#372 Fix bitpacked activation pass when interacting with fused BN/activation.
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/transforms/optimize.cc
Labels: bug

#374 Make sure end2end tests fail when assertions fail in C++
  larq_compute_engine/tests/end2end_test.py
  larq_compute_engine/tests/end2end_verify.cc
Labels: internal-improvement

#376 (Slightly) faster Aarch64 bitpacking.
  larq_compute_engine/core/packbits_aarch64.h
Labels: internal-improvement

#377 Fix weight bitpacking which could lead to non-deterministic behaviour
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/transforms/optimize.cc
Labels: bug

#378 Fix weight bitpacking which could lead to non-deterministic behaviour
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/transforms/optimize.cc
Labels: bug

#379 :arrow_up: 0.3.1
  setup.py
Labels: skip-changelog

#380 Add testing script for faster model conversions debugging
  larq_compute_engine/tests/BUILD
  larq_compute_engine/tests/convert_model.py
Labels: internal-improvement

#381 Upgrade github/actions
  .github/tools/release_linux.sh
  .github/workflows/lint.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#375 Add pattern to ensure post_activation_multipliers are always positiv
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/transforms/optimize.cc
  larq_compute_engine/mlir/transforms/optimize_patterns.td
Labels: internal-improvement

#373 Rename BConv attributes to follow TFLite more closely
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/ir/lce_ops.td
  larq_compute_engine/mlir/tests/op-removal.mlir
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/tests/quantize.mlir
  larq_compute_engine/mlir/transforms/op_removal_patterns.td
  larq_compute_engine/mlir/transforms/optimize_patterns.td
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/prepare_tf.cc
  larq_compute_engine/mlir/transforms/quantize_patterns.td
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_params.h
  larq_compute_engine/tflite/tests/bconv2d_op_model.h
Labels: breaking-change

#382 Remove filter_format attribute from IR and bconv kernel
  larq_compute_engine/mlir/ir/lce_ops.td
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/tests/quantize.mlir
  larq_compute_engine/mlir/transforms/op_removal_patterns.td
  larq_compute_engine/mlir/transforms/optimize_patterns.td
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/quantize_patterns.td
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/tests/bconv2d_op_model.h
Labels: internal-improvement

#385 Support dilated convolutions in converter
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/transforms/prepare_tf.cc
Labels: feature
