Repository larq/compute-engine, pull requests merged in 2020-07, with the labels that each got.

#422 Fix int8 outputtransform
  larq_compute_engine/core/bconv2d_output_transform.h
  larq_compute_engine/tests/end2end_test.py
  larq_compute_engine/tflite/kernels/bconv2d.cc
  larq_compute_engine/tflite/kernels/bconv2d_output_transform_utils.h
  larq_compute_engine/tflite/kernels/bconv2d_params.h
Labels: bug

#426 Refactor OutputTransform with template types
  larq_compute_engine/core/bconv2d_impl_ref.h
  larq_compute_engine/core/bconv2d_output_transform.h
Labels: internal-improvement

#430 Update the unittest error threshold
  larq_compute_engine/tflite/tests/bconv2d_test.cc
Labels: internal-improvement

#434 Update lce_register.cc
  larq_compute_engine/tflite/kernels/lce_register.cc
Labels: dependencies

#436 Test converter against TF 2.3
  .github/workflows/unittests.yml
Labels: internal-improvement

#437 Remove unused packbits_arm32
  larq_compute_engine/core/BUILD
  larq_compute_engine/core/packbits_arm32.h
  larq_compute_engine/core/tests/BUILD
  larq_compute_engine/core/tests/bgemm_arm32_tests.cc
  larq_compute_engine/core/tests/packbits_arm32_tests.cc
  larq_compute_engine/tests/BUILD
  larq_compute_engine/tests/cc_tests_arm32_qemu.sh
Labels: internal-improvement

#438 Test against Python 3.8 by default on CI
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#441 Use a 32-column C++ kernel layout when writing bitpacked output.
  larq_compute_engine/core/bgemm_kernels_common.h
  larq_compute_engine/core/bgemm_kernels_ruy.h
Labels: internal-improvement

#442 Add `make_unsigned` to `unpack_matrix` type
  larq_compute_engine/core/packbits.h
Labels: internal-improvement
