Repository larq/compute-engine, pull requests merged in 2020-02, with the labels that each got.

#229 Add release notes bot
  .github/pr_labels.yml
  .github/release-drafter.yml
  .github/workflows/release-notes.yml
Labels: internal-improvement

#230 Fix is-binary check
  larq_compute_engine/mlir/transforms/prepare_patterns.td
  larq_compute_engine/mlir/transforms/prepare_tf.cc
Labels: bug

#232 Update actions/checkout@v2
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#233 Build wheels for macOS 10.13
  .github/workflows/release.yml
  build_pip_pkg.sh
Labels: bug

#234 Bump 0.1.1
  setup.py
Labels: skip-changelog

#235 QuickNet .h5 links
  README.md
Labels: documentation

#236 fix links in second table
  README.md
Labels: documentation

#237 Improve converter API docs
  larq_compute_engine/mlir/python/converter.py
Labels: documentation

#239 Move docs to larq/docs
  docs/README.md
  docs/build.md
  docs/build_arm.md
  docs/converter.md
  docs/inference.md
  docs/quickstart_android.md
Labels: documentation

#238 build LCE compatible TensorFlow Lite android AAR target
  .github/workflows/unittests.yml
  configure.sh
  larq_compute_engine/tflite/java/BUILD
  larq_compute_engine/tflite/java/build_lce_aar.sh
  larq_compute_engine/tflite/java/lce_ops_jni.cc
  third_party/install_android.sh
Labels: feature

#241 remove LCE tflite legacy python API
  .github/workflows/unittests.yml
  larq_compute_engine/tflite/python/README.md
  larq_compute_engine/tflite/python/bconv2d_inference_test.py
  larq_compute_engine/tflite/python/bsign_test.py
  larq_compute_engine/tflite/python/inference_test_base.py
  larq_compute_engine/tflite/python/largemodel_test.py
Labels: internal-improvement

#243 remove legacy TF ops
  larq_compute_engine/BUILD
  larq_compute_engine/tf/__init__.py
  larq_compute_engine/tf/kernels/bconv2d.cc
  larq_compute_engine/tf/kernels/sign_kernels.cc
  larq_compute_engine/tf/ops/BUILD
  larq_compute_engine/tf/ops/bconv_shape_inference.cc
  larq_compute_engine/tf/ops/bconv_shape_inference.h
  larq_compute_engine/tf/ops/compute_engine_ops.cc
  larq_compute_engine/tf/python/__init__.py
  larq_compute_engine/tf/python/modelconverter.py
  larq_compute_engine/tf/python/ops/__init__.py
  larq_compute_engine/tf/python/ops/bconv2d_ops_test.py
  larq_compute_engine/tf/python/ops/bsign_ops_test.py
  larq_compute_engine/tf/python/ops/compute_engine_ops.py
  larq_compute_engine/tf/python/utils.py
Labels: internal-improvement

#246 Bitpack weights only on the first run
  larq_compute_engine/tflite/kernels/bconv2d.cc
Labels: bug

#242 Remove unused explicit padding argument
  larq_compute_engine/mlir/ir/lce_ops.td
  larq_compute_engine/mlir/transforms/optimize_patterns.td
  larq_compute_engine/mlir/transforms/prepare_patterns.td
Labels: internal-improvement

#247 Use vectors instead of tflite temp buffers
  larq_compute_engine/tflite/kernels/bconv2d.cc
Labels: bug

#249 update the pixel phone benchmark results
  README.md
Labels: documentation

#248 Add tests for MLIR passes
  .github/workflows/unittests.yml
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/tests/BUILD
  larq_compute_engine/mlir/tests/lit_test.bzl
  larq_compute_engine/mlir/tests/optimize.mlir
  larq_compute_engine/mlir/tests/prepare-tf.mlir
  larq_compute_engine/mlir/tests/run_lit.sh
Labels: internal-improvement

#250 :arrow_up: v0.1.2
  setup.py
Labels: skip-changelog

#251 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: internal-improvement, skip-changelog
