Repository larq/compute-engine, pull requests merged in 2021-03, with the labels that each got.

#610 Statically link GLIBC in benchmark binaries
  .github/workflows/release.yml
Labels: bug

#616 Remove spectrum badge since we moved to GitHub discussions
  README.md
Labels: documentation

#617 Run AAR build on Ubuntu 18.04
  .github/workflows/release.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#618 :arrow_up: CI dependencies
  .github/workflows/lint.yml
  .github/workflows/unittests.yml
Labels: internal-improvement

#622 Add -lm link option to lce_benchmark_model
  larq_compute_engine/tflite/benchmark/BUILD
Labels: internal-improvement

#623 Fix lce_benchmark_model linking on Aarch32
  larq_compute_engine/tflite/benchmark/BUILD
Labels: internal-improvement
