Repository larq/compute-engine, pull requests merged in 2022-04, with the labels that each got.

#721 Update lint package versions
  test-requirements.txt
Labels: dependencies

#720 Make assembly compatible with clang
  larq_compute_engine/core/bgemm/kernels_arm32.h
Labels: internal-improvement

#727 Fix segfaults in benchmark binaries when setting num_threads > 1
  larq_compute_engine/tflite/benchmark/BUILD
Labels: bug

#663 Update QuickNet documentation.
  README.md
Labels: documentation

#729 Deal with non-deterministic input order for interpreter test
  larq_compute_engine/tflite/tests/interpreter_test.py
Labels: bug

#731 Fix build cache for windows release build
  .github/workflows/release.yml
Labels: internal-improvement

#732 :arrow_up: 0.7.0
  setup.py
Labels: skip-changelog

#733 Add Python 3.10 to release builds
  .github/workflows/release.yml
Labels: internal-improvement

#734 Remove `weak` attribute for `RegisterSelectedOps`
  larq_compute_engine/tflite/benchmark/lce_benchmark_main.cc
Labels: internal-improvement
