Repository larq/compute-engine, pull requests merged in 2023-08, with the labels that each got.

#786 Build wheels for Python 3.11
  .github/workflows/release.yml
  .github/workflows/unittests.yml
Labels: feature

#787 Drop support for Python <=3.8 and TensorFlow <=2.4
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/unittests.yml
  larq_compute_engine/mlir/python/converter.py
  larq_compute_engine/mlir/python/converter_test.py
  larq_compute_engine/tests/end2end_test.py
  larq_compute_engine/tflite/python/interpreter_base.py
  setup.py
Labels: breaking-change

#789 Upgrade Android NDK version
  .github/workflows/release.yml
  .github/workflows/unittests.yml
  configure.py
  third_party/install_android.sh
Labels: internal-improvement

#785 :arrow_up: 0.13.0
  setup.py
Labels: skip-changelog

#791 Use command parameter files when compiling on Windows
  .tensorflow.bazelrc
Labels: internal-improvement
