Repository larq/compute-engine, pull requests merged in 2023-07, with the labels that each got.

#776 Add support for multiple subgraphs in some of the Python MLIR utils
  larq_compute_engine/mlir/python/util.py
Labels: feature

#777 Quantized INT8 detection postprocess op support in the converter
  larq_compute_engine/mlir/BUILD
  larq_compute_engine/mlir/tests/BUILD
  larq_compute_engine/mlir/tests/detection_postprocess.mlir
  larq_compute_engine/mlir/tf_tfl_passes.cc
  larq_compute_engine/mlir/transforms/detection_postprocess.cc
  larq_compute_engine/mlir/transforms/passes.h
Labels: skip-changelog

#780 Use static library in cmake build
  CMakeLists.txt
Labels: internal-improvement
